### ISSUE TITLE
Chat Panel

### ISSUE THREAD

**Issue by ValentinRonsseray** [Pierrad/obsidian-github-copilot#45] opened 2024-10-23 06:46 UTC
Hello,

A Copilot chat panel like the one in VSCode would be a great improvement for this fantastic plugin.

Cheers,

**Comment by Pierrad** [comment] 2024-10-26 07:30
Hi, thanks for using the plugin! As this idea is a duplicate of the #42, I will close this one but you can follow the rest on the #42 issue.

**Closed** 2024-10-26 07:30 UTC
Labels: duplicate, enhancement
